version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    depends_on:
      - db
    restart: unless-stopped
    # No code volume mounts in production

  db:
    image: postgres:14-alpine
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 