version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./app:/app
      - /app/node_modules

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userbios
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: